### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by yodasw16** [atom/apm#103]
I am behind a work proxy which causes me to get this error when I try to view packages. I've had the same error in the past when using npm or Bower. For npm I am able to do `npm config set strict-ssl false` on the command line to make it stop checking ssl certs. Similarly for Bower I can set strict-ssl to false in a bower.rc file. It would be cool if there were a way to disable checking ssl certs in Atom so us corporate stooges can use it :)

**Comment by ashjas** [comment]
How to do this on windows?

**Comment by Energy1011** [comment]
@ashjas You only need to put this line in the file ~/.atom./apmrc :
```
strict-ssl = false
```
On windows this path is like C:\Users\<your_username>\.atom  also you can copy the file from
C:\Users\<your_username>\.atom\.apm  to the parent folder in your file explorer because windows explorer doesn't give permission to create hidden-unix-style files easily in windows explorer, you can get an error like "You need to write a name for file".

I tried it at work behind a firewall and it works .

**Comment by ChavahJ** [comment]
Thanks, @ashjas! That really helped me.

**Comment by GenweiWu** [comment]
saved my day

**Comment by chrisjaimes** [comment]
Although @Energy1011 solution works. For me it was enough to turn off the VPN and reinstall again.
