### ISSUE TITLE
Creating new version failed: Not found

### ISSUE THREAD

**Issue by tokejepsen** [atom/apm#272]
Trying to publish this repo for the first time;

https://github.com/tokejepsen/atom-nuke

Error;

```
Publishing Nuke@v0.1.0 failed
Creating new version failed: Not found
```

Have published before with the same setup, without a problem.

**Comment by thedaniel** [comment]
Hm, I'll take a look at this. In any case, the error message should be better.

**Comment by tokejepsen** [comment]
Any news on this? The latest version of apm still produces this error.

**Comment by thedaniel** [comment]
Sorry about this, I suspect it's related to a bug connected to unpublishing packages. That is to say, someone in the past published `nuke` and then unpublished it, and the API gives a bad/useless error message.

**Comment by tokejepsen** [comment]
ahh, does that mean I should find another name for the package? or wait for a fix?

**Comment by thedaniel** [comment]
I have some security concerns about packages being unpublished and then the name taken by something else,  leading to users with the old packages getting auto-updated to completely unrelated code (because the API only distinguishes unique packages by name right now) so I would suggest finding a new name. I don't know if/when we will find the time to address the issue. We'll definitely make the error message though.
