### ISSUE TITLE
`apm publish` cannot find Git tag

### ISSUE THREAD

**Issue by matthojo** [atom/apm#290]
## Problem
When trying to publish an update to the https://github.com/matthojo/language-stylus Atom package, I keep getting an error saying `Creating new version failed: Git tag not found`. This happens when using both `npm publish patch` and also `npm publish --tag v0.5.1`.

The tags are present locally an online and are also created and pushed when using `npm publish`.
![screen shot 2015-02-09 at 10 28 09](https://cloud.githubusercontent.com/assets/367517/6104560/6d39a7d4-b046-11e4-9105-fdd9308726a8.png)

## Expected 

The version tag should be found by `apm` and published.

## Information

* **OS:** Mac OS X 10.10.2
* **apm:**  0.134.0
* **npm:**  2.3.0
* **node:** 0.10.35
* **python:** 2.7.6
* **git:** 2.2.1

**Comment by matthojo** [comment]
I just tried again with a newer tag, but still doesn't work ( https://github.com/matthojo/language-stylus/tree/v0.5.2).

Thanks for the quick response.

**Comment by izuzak** [comment]
@matthojo Seems like you changed the name of the package from `stylus` to `language-stylus`:

https://github.com/matthojo/language-stylus/commit/bf2103c62fb88c1124de49528665baea2040b7c9

However, there's already a package under that name:

https://atom.io/packages/language-stylus

https://github.com/devongovett/atom-stylus/blob/master/package.json

Since there's [no such tags in that repository](https://github.com/devongovett/atom-stylus/tags), the apm command is failing with that message. It should probably be detecting this problem and communicating it in a different way. /cc @thedaniel

**Comment by izuzak** [comment]
Also, notice that there's an api to change the name of package:

```
$ apm publish --help

Usage: apm publish [<newversion> | major | minor | patch | build]
       apm publish --tag <tagname>
       apm publish --rename <new-name>

Publish a new version of the package in the current working directory.

...

If a new name is provided via the --rename flag, the package.json file is
updated with the new name and the package's name is updated on Atom.io.
```

I haven't used that before, but I'm _guessing_ it would have shown you a different error which would point to the problem more clearly.

**Comment by matthojo** [comment]
@izuzak Thank you, I have renamed the package back and all is updating fine :+1:

I'll be more observant of renaming to an existing package next time!

Thank you :)
