### ISSUE TITLE
Feature request: Sorting Packages & Themes

### ISSUE THREAD

**Issue by boustanihani** [atom/apm#303]
Could you please **allow sorting** search results on https://atom.io/packages & https://atom.io/themes by the **number of downloads** and the **number of stars** ?

And maybe also inside the Atom Editor...

**Comment by jwerre** [comment]
:+1:

**Comment by simurai** [comment]
This is already possible on atom.io, but kinda hidden and not that obvious:

1. Click on the "See all" link
![screen shot 2015-06-30 at 1 23 55 pm](https://cloud.githubusercontent.com/assets/378023/8423875/6a21c42e-1f2b-11e5-8efb-5a0a12b18fd2.png)

2. Then change to "Most Downloads"
![screen shot 2015-06-30 at 1 24 21 pm](https://cloud.githubusercontent.com/assets/378023/8423877/7eb0af36-1f2b-11e5-81ad-0accffe2f1b1.png)

Maybe there could be an "All packages" as a 4th section, but instead of having the package cards, it could have the dropdown to filter or just links.

**Comment by boustanihani** [comment]
The "See all" link disappears when you search for something, there is still no way to sort search results...

Currently you can only sort all packages without filtering...

**Comment by simurai** [comment]
@boustanihani I see, I missed the "search results" part.

**Comment by kenden** [comment]
+1 
Allowing to order packages/themes by number of stars / number of downloads from the Settings inside Atom would really help in choosing one.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#9

**Comment by mibamur** [comment]
## Command line solution
https://github.com/atom/atom.io/issues/9#issuecomment-229373728
