### ISSUE TITLE
bad option: --harmony_collections

### ISSUE THREAD

**Issue by romu70** [atom/apm#481]
Hi,
Fedora 23 here, Atom 1.3.2, as soon as I run "apm" (just this simple command, no package specified), I get the message:

```bad option: --harmony_collections```

Of course, same error when trying to install a plugin for real.

**Comment by koppeex** [comment]
I got same message when I build atom on Windows7.

```
$ script/build
Node: v4.2.4
npm: v2.13.3
Python: v2.7.5
Installing build modules...
Installing apm...
node.exe: bad option: --harmony_collections
```

**Comment by ZombieHippie** [comment]
Same error here on Windows 8.1
```
Node: v5.5.0
npm: v2.13.3
Python: v2.7.9
Installing build modules...
=> Took 5280ms.

Installing apm...
=> Took 984ms.

Deleting old packages...
node.exe: bad option: --harmony_collections

```

**Comment by 50Wliu** [comment]
This is because apm currently requires a very ancient version of Node for reasons documented here: #410. apm bundles its own version of Node, so if you are running into this issue, please make sure you didn't symlink a newer version of Node by accident to apm (the COPR Atom repository incorrectly does this I believe).

@koppeex, @ZombieHippie: did you attempt to alter the version of Node that apm uses?

@romu70: Did you install Atom from the COPR repo?

**Comment by romu70** [comment]
@50Wliu didn't remember. And to be honest, I removed Atom and switched to VsCode.

**Comment by koppeex** [comment]
@50Wliu 
I tried old node version. but I could not build them.

```
$ script/build
Node: v0.10.43
npm: v1.4.29
Python: v2.7.5
Installing build modules...
gypnpm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=c:\\atom\\build\\.npmrc" "install" "--loglevel" "erro
r"
npm ERR! cwd c:\atom\build
npm ERR! node -v v0.10.43
npm ERR! npm -v 1.4.29
npm ERR! code ELIFECYCLE
npm
```

**Comment by ZombieHippie** [comment]
Yes Koppe Ex, that is expected, because as I understand it, APM ships with
its own version of node. You need to make sure that the version of node
that it ships with isn't being lost. Once you have Python 2.7 and your
build tools set up, try rebuilding everything and forcing APM to redownload
its node binary.

**Comment by ZombieHippie** [comment]
You should be able to build everything with a node version at 4.x or above.
