### ISSUE TITLE
Install packages system-wide

### ISSUE THREAD

**Issue by probonopd** [atom/apm#506]
The readme mentions that packges are installed to `~/.atom/packages`. What am I supposed to do if I am an administrator who wants to install packages system-wide, so that they end up in `/usr` (possibly `/usr/share/atom/resources/app.asar`) rather than `/home`? 

Reason for asking:
I would like to provide an [AppImage](http://appimage.org/) that comes with some packages bundled out-of-the-box.

**Comment by probonopd** [comment]
The following is not quite working yet:

```
sudo apt-get update
sudo apt-get -y install npm nodejs-legacy

npm install asar

./node_modules/asar/bin/asar extract /usr/share/atom/resources/app.asar extracted

cp -r  /home/me/.atom/packages/* extracted/node_modules/ ### This is probably wrong?

# Replace symlinked stuff with the originals
rsync extracted/ extracted_fixed  -a --copy-links -v

 ./node_modules/asar/bin/asar pack extracted_fixed/ /usr/share/atom/resources/app.asar
```

**Comment by lee-dohm** [comment]
Bundling community packages inside a custom generated `app.asar` would be very confusing from a support perspective (for instance, one of your users reports a bug on the Atom repositories or posts a question on Discuss). I do think that having a story for installing community packages machine-wide is a useful thing to have on the other hand, even though it isn't something we've considered previously.

**Comment by probonopd** [comment]
I am not necessarily looking to install community packages inside a custom generated `app.asar`, it would be equally sufficient to be able to have some location relative to the atom executable in addition to `~/.atom/packages` as an install location for `apm`. Invoking `sudo apm --system-wide` or something along these lines could then use the aforementioned system-wide location.

**Comment by tjallingran** [comment]
I'd like to have this feature as well.

We use a custom Ubuntu live image. It's created using a script that extracts the original .iso, `chroot`s into the filesystem and adds and removes packages and configuration files. One of the applications it installs is Atom. We'd like the script to also install a predefined set of atom packages that should be available to all (future) user accounts, so that our users have all required packages available from the start.

**Comment by thomasjo** [comment]
@tjallingran Your concrete use case can trivially be solved by leveraging [`/etc/skel`](http://www.linfo.org/etc_skel.html) functionality.

**Comment by swirly** [comment]
Would be interested by this feature in a wondows environment also. Why ? Because we use roaming profile and each time a user logs in, 300MB gets copied over the network to load Atom packages. Much too long indeed.
Installing system wide would be great. I Installed Atom system wide with a zip and a script. Packages is the next step.

**Comment by lee-dohm** [comment]
Thanks very much for the feedback. While we understand that this would be useful in some scenarios, it isn't something that we are planning to work on implementing or are willing to maintain at this time. Because of this, we won't be accepting any pull requests to implement this feature.

Thanks again for the interest and the time taken to make us aware of everyone's use case.
