### ISSUE TITLE
How to install shell commands for "Atom for Windows"?

### ISSUE THREAD

**Issue by hypogaea** [atom/apm#547]
I have installed Atom for Windows, but there is no shell commands in my local PC

**Comment by 50Wliu** [comment]
@hypogaea How did you install Atom?

**Comment by hypogaea** [comment]
I just run "Windows Installer" downloaded from [HERE](https://atom.io/), the red button with "Download Windows Installer"

**Comment by fibric** [comment]
On Windows, if installed correct, Atom's CLI `atom` should be located in `C:\Users\<user>\AppData\Local\atom\bin`.

You should see it somewhere in `echo %PATH` output.

**Comment by hypogaea** [comment]
@fibric Thx a lot

**Comment by damieng** [comment]
@hypogaea Did it not add that folder to your PATH?  If it did not could you provide some more information - such as are you on a corporate network that might have applied security policies?

**Comment by hypogaea** [comment]
Thx @damieng , @fibric had given me the right method.

**Comment by hypogaea** [comment]
resolved

**Comment by hypogaea** [comment]
@damieng No, I use it on my own computer at home.

**Comment by hypogaea** [comment]
Resolved #547

**Comment by hypogaea** [comment]
Close #547

**Comment by hypogaea** [comment]
closed #547

**Comment by hypogaea** [comment]
Closed #547

**Comment by bloodstrike** [comment]
Stumbled across this issue looking for something else. Installed Atom 1.8 from the official installer on Windows 7 (32bit). PATH does contain C:\Users\\\<user>\AppData\Local\atom\bin, **_however_** that directory does not exist. Here is the contents of AppData\Local\atom:

```
Directory of C:\Users\<user>\AppData\Local\atom

06/08/2016  10:48 AM    <DIR>          .
06/08/2016  10:48 AM    <DIR>          ..
06/08/2016  10:45 AM    <DIR>          app-1.8.0
06/08/2016  10:48 AM           186,361 app.ico
06/08/2016  10:45 AM    <DIR>          packages
06/08/2016  11:05 AM             8,754 SquirrelSetup.log
06/06/2016  02:52 PM         1,526,024 Update.exe
               3 File(s)      1,721,139 bytes
               4 Dir(s)  215,244,148,736 bytes free
```

I'm going to try to uninstall all trace of Atom and reinstall, but I wanted to update this issue with what I'm seeing currently.

**Comment by damieng** [comment]
We've seen reports of this a few times but haven't yet determined why it happens. I think we need to put more logging in. It's being tracked over at https://github.com/atom/atom/issues/11450

**Comment by alimary** [comment]
I'm having the same problem in windows, but the file is not in any of the directories you have listed.

**Comment by ewillstudios** [comment]
@alimary i just had this same issue. The link given by @damieng has a solution you may want to try.

C:\Users\*_username_*\AppData\Local\atom\app-1.8.0\resources\cli

**Comment by stretchtiberius** [comment]
I have installed atom 1.10 on 5 or so computers over the last couple weeks and ran into this problem on a couple of them. On Windows 7 and above, add the ```%LOCALAPPDATA%\Atom\bin``` to your user ```PATH``` variable. You test it out from the command line by running the following command:
```SET PATH=%PATH%;%LOCALAPPDATA%\Atom\bin```
Then you should be able to run Atom directly from the command line.

If you want to make it permanent, you will need to change the ```PATH``` variable in the system settings.

**Comment by damieng** [comment]
@stretchtiberius are you using the atomsetup.exe installer or the windows zip package?

If using the installer can you try removing the path you added on one then doing this;

```
cd %localappdata%
cd atom
cd app-1.10.0 (or whatever version)
atom.exe --squirrel-install
```

and let me know if it reports any kind of error.  It seems for some people it is unable to add to the PATH but we're not sure why.

**Comment by stretchtiberius** [comment]
Yes, I was using AtomSetup.exe. Unfortunately, I was setting up Atom on some friends' PCs. Next time I have access to a computer where the AtomSetup.exe failed to modify the path, I'll report back to you. Atom was automatically added to the path on my machine.

**Comment by stretchtiberius** [comment]
@damieng, I ran the commands you requested on a Windows 7 machine that did not get atom added to the path during the initial install of AtomSetup.exe. There was no output when I ran ```atom.exe --squirrel-install``` and atom was then properly added to the ```PATH```.

**Comment by damieng** [comment]
Thanks for that @stretchtiberius I think then it confirms that part is working. I suspect there is a sequence where atom.exe isn't run with --squirrel-update

**Comment by acroyear** [comment]
It isn't working for me. Windows 10. In the Squirrel log file I see the following:

2016-12-21 16:17:55> Program: Fetching update information, downloading from https://atom.io/api/updates?version=1.12.7
2016-12-21 16:17:55> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\joe\AppData\Local\Temp\.squirrel-lock-1D277DA284EB3AACB10CCF052286D2DCC6EC9B7D: System.IO.IOException: The process cannot access the file 'C:\Users\joe\AppData\Local\Temp\.squirrel-lock-1D277DA284EB3AACB10CCF052286D2DCC6EC9B7D' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2016-12-21 16:17:55> CheckForUpdateImpl: Generated new staging user ID: 0a4ed32b-5285-51e1-ab7c-69f818906d02
2

A slightly different error happened when I installed 0.11 first and then upgraded to 0.12 - it was running 12, but the 11 folders were still there and the command line stuff still didn't get set.

I'm wondering if a windows 10 security thing? should i uninstall and install as administrator?

**Comment by damieng** [comment]
Hi @acroyear can you create a new issue for your problem over at atom/atom - it's not really related to this issue (which I'm going to lock as there is never a need to "Install Shell Commands" for Atom on Windows and it's pinging 9+ people from this thread).

As a quick heads-up I'd suggest taking a look at any 3rd-party (non-Microsoft) security/AV solutions as they can interfere with moving our binary files during installation. Failing that you can just grab the atom-windows.zip from releases, unpack it where you want and just add the resources\cli folder to your PATH.
