### ISSUE TITLE
apm help update shows wrong messages

### ISSUE THREAD

**Issue by ThatKorean** [atom/apm#552]
Yeah, `apm help update` shows help messages for `upgrade` command.
Why not plug in `options.command` instead of hardcoded `upgrade`?

**Comment by thomasjo** [comment]
The primary command name is `upgrade`, whereas `outdated` and `update` are aliases. When displaying help messages, it is not common practise to use the user-specified aliased command name. Even apm's closely related "cousin" npm behaves the same way.

I'm closing this as `wontfix` because this is common practise, and is not worth the effort considering all the edge cases this will spawn. /cc @atom/feedback
