### ISSUE TITLE
Consider `yarn` over `npm`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [atom/apm#658]
[`yarn`](https://github.com/yarnpkg/yarn) is a notably faster alternative to `npm`.  Since `node@4.0.0` [seems to be](https://github.com/atom/apm/blob/master/.travis.yml#L8) the minimum required `node` version for `apm`, would this be considered?

**Comment by lee-dohm** [comment]
We have considered it and discussed it with one of the yarn maintainers. Currently, there are some problems with yarn around transitive dependencies among others that block any adoption. We'll keep on top of it as time passes though.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by KSXGitHub** [comment]
How's about [pnpm](https://pnpm.js.org/)?
https://github.com/atom/atom/issues/17655
