### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by vitalyavolyn** [atom/apm#680]
### Description

`DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.` shows up every time i'm installing a package

### Steps to Reproduce

1. Install some package with CLI or do `apm --version`

**Expected behavior:** [What you expect to happen]
no deprecation warning 

**Actual behavior:** [What actually happens]
shows up every time

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
```
$ apm --version
(node:20830) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.15.2
npm  4.1.2
node 7.4.0 x64
python 3.6.0
git 2.11.0
$ atom --version
Atom    : 1.13.1
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.

**Comment by byronigoe** [comment]
I get this error when I'm bootstrapping atom from source:
```
C:\code\atom>script\bootstrap
Node:   v8.10.0
Npm:    v5.3.0
Python: v2.7.14
Installing script dependencies
Installing apm
(node:21784) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing modules done
```
