### ISSUE TITLE
apm  install  not works

### ISSUE THREAD

**Issue by seajean** [atom/apm#688]
### Description

after I updated some plugins,restarted atom then  I found I was not be able to install plugins anymore, I try  to run  ` apm install terminal-plus`  from shell  and got errors below.

```shell
Installing terminal-plus to /Users/Seajean/.atom/packages 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp http 200 https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at TLSWrap.onread (net.js:552:26)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/Seajean/.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by anomaly256** [comment]
@rsese.. I've come across several issues now where you've closed them out of hand because they didn't follow the template without actually addressing the problem itself.  I must say this is counter productive and only serves to increase animosity between devs and users of Atom.  I get what you're trying to do but given the number 'closed' but *not* 'fixed' issues around iojs I've come across researching my own issue I think it's safe to declare this as dysfunctional.

Please don't ignore issues just because they don't follow the template.

**Comment by rsese** [comment]
I hear you @anomaly256 :+1:  I can definitely see how that can be discouraging in some cases.  I've tried to tweak my approach over time to try and work with folks in some cases even if they don't fill out the template while nudging them to use the template for future issues since the template is super helpful for us.  And I can see how my reply above also isn't super clear that opening a new issue with the template filled out is definitely welcome  (I've tweaked my reply since to make that more clear).

You make good point too about closing multiple similar issues that didn't follow the template but all together point towards a specific problem - I should do a better job keeping that in mind if I come across a similar situation.

Thanks again for the feedback (and for opening a new issue with about iojs problem) - if you have suggestions about tweaking the process for working with people who open issues but don't use the template, I'd love to hear it and I can share it with the other maintainers.

**Comment by anomaly256** [comment]
Thanks for responding @rsese.  I know it's a difficult problem to approach.  One thought that comes to mind might be tagging such issues as needing more info, responding with instructions for using the template and giving the reporter some time to respond.  If they never reply back with the information the template gathers then maybe close it as stale after 30 days or some other practical time period.  When searching for issues, Github's default is to only search open issues.  (I only happened to search in closed to see if it had been resolved in a beta release or head).  I think this will both reduce duplicates (at least in this instance) and let people provide more info in the right places over time.  Cheers

**Comment by rsese** [comment]
I feel like if we adjust a bit, things could go a bit smoother in the process so thanks for sharing your ideas @anomaly256, I really appreciate it :v:  In particular I kinda like this flow you described:

>  responding with instructions for using the template and giving the reporter some time to respond. If they never reply back with the information the template gathers then maybe close it as stale after 30 days or some other practical time period.

**Comment by 50Wliu** [comment]
I've been thinking about that as well.  Maybe we can update probot-stale to warn after a month and close in 2 months?

**Comment by rsese** [comment]
> Maybe we can update probot-stale to warn after a month and close in 2 months?

Yeah that time period sounds like a nice ballpark - would love to chat more next week Tuesday if you're stopping by the meeting @50Wliu :v:

**Comment by seajean** [comment]
@rsese After you tell me to fill the template, I  uninstalled  and reinstalled ATOM(these steps are easier than filling the template), and it works.  So I forget about this. . ATOM is always not  so stable,  opening large js files always hang up, Updating ATOM always make some plugins stop to work, but is was fine, I have got used to this pain.
