### ISSUE TITLE
I don't publish package

### ISSUE THREAD

**Issue by mustafakucuk** [atom/apm#699]
Hi,
I development a package but I don't publish.

Error : Package must be in a Git repository before publishing: https://help.github.com/articles/create-a-repo

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

If you can post your question to our Discuss forum, we should be able to help you out there:

https://discuss.atom.io

On Discuss, there are a bunch of helpful community members that should be willing to point you in the right direction [1].

[1]: https://discuss.atom.io/t/apm-publish-minor-doesn-t-work/18134
