### ISSUE TITLE
Bad handling of `repository` field in `package.json`

### ISSUE THREAD

**Issue by joaomlneto** [atom/apm#777]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Bad handling of `repository` field in `package.json`.
Only supports a subset of what's accepted by `npm`.

The code to resolve the Git repository is quite limited [src/packages.coffee](https://github.com/atom/apm/blob/master/src/packages.coffee).
This is used by the `publish` process [src/publish.coffee](https://github.com/atom/apm/blob/478f7be389cdb1bf38c6f284d7631cad04e62e91/src/publish.coffee#L87).
I'm guessing it's used in many other parts of `apm`, and (1) makes `apm` work exclusively with GitHub (not sure if intentional *wink wink*) and (2) reduces `npm` compatibility with `apm`

It should allow allow specifying the repository URL other than using `https://` prefix.

It should allow specifying:
- `"repository": "github:atom/apm"` or even more-shorthand:
- `"repository": "atom/apm"` for github-hosted projects. Should also allow others like:
-  `"repository": { "type": "git", "url": "git@github.com:atom/apm.git" }`
- ...

In addition, should support non-GitHub hosted packages. I don't see the limitation besides resolving the URLs:
`git+ssh://user:password@githosting.supercompany.com/atom/apm`

Also, should allow shorthand for services other than GitHub (also supported by `npm`):
- BitBucket
  - `bitbucket:atom/apm`
  - `git+ssh://git@bitbucket.org/atom/apm.git`
  - `git+ssh://git@bitbucket.org/atom/apm#foo/bar`
  - ...
- GitLab
  - `gitlab:atom/apm`
  - `git+ssh://git@gitlab.com/atom/apm.git`
  - `git+ssh://git@gitlab.com/atom/apm.git#foo/bar`
  - ...

Rather than being limited to this structure:
```
  "repository": {
    "type": "git",
    "url": "https://github.com/atom/apm.git"
  },
```

Also: `npm` also supports `gist` references. `apm` should support them (if possible).

**If you think this is worthwhile (as many people seem to agree), you can tentatively assign this to me :-)**

### Steps to Reproduce

As described in https://github.com/Glavin001/atom-beautify/pull/2063

1. Set `repository` to `"github:atom/apm"`
2. `apm publish patch`

**Expected behavior:** `apm publish` succeeding with `"repository": "github:atom/apm"`

**Actual behavior:**
```
❯ apm publish patch
Preparing and tagging a new version ✓
Pushing v0.32.1 tag ✗
ssh: Could not resolve hostname github: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Reproduces how often:** 100%

### Versions

This is sort of irrelevant, but... :-)
```
$ atom --version
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
$ apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.10
git 2.14.3
```

### Additional Information

Related problems reported in #302, #580, #753 and #754 
This rabbit hole started on https://github.com/Glavin001/atom-beautify/pull/2063

**Comment by lee-dohm** [comment]
Thanks for the detailed report :+1:

As I stated in #754, while we understand people may want to use other code hosts for their packages, we aren't going to invest in adding or maintaining support for that. People can still install packages from other code hosts by installing using the Git support but they won't be listed on atom.io.

With regard to supporting all the various Git repository notations that npm does, there are a number of things that npm does that apm doesn't. They are very similar tools and we used npm to jump start our design of apm early on but since that time they have slowly diverged. As you pointed out in https://github.com/Glavin001/atom-beautify/pull/2063, other bits of code in Atom depend on that repository field being a GitHub `https:` repository URL, so this isn't as simple as just changing it in apm. Because of this, we aren't going to be changing how this field is handled, especially since the repository field is set once or maybe a tiny handful of times in the lifetime of a package. There isn't a lot of payoff for the amount of effort this would require.

Thanks very much for your interest and for the detailed thoughts!
