### ISSUE TITLE
Blocked from publishing releases with versions prefixed by `v`

### ISSUE THREAD

**Issue by Alhadis** [atom/apm#781]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done the usual yadda-yadda (elided for brevity).

### Description
I'll let the error explain itself...

~~~console
$ apm publish --tag v1.0.0
Creating new version failed: You specified a tag with the version number '1.0.0', but the version number in package.json is 'v1.0.0'. The version numbers must agree before you can publish.
~~~

Related issue: [`#724`](https://github.com/atom/apm/issues/724)

**Expected behaviour:**  
Running `apm publish` and having it figure out there's a new tag, intelligently matching it with what `package.json` uses, and going *"Hey, I got this. Published as v1.0.0! Tada!"*

**Actual behaviour:**  
I'm reduced to passing a tag manually in a switch to avoid having `apm` rape `package.json`'s formatting, which no longer works due to a remote issue in `atom.io`'s server.

So instead, I'm forced to
1. Delete the signed release-tag (both locally and on GitHub)
2. Amend the commit `Release v1.0.0` so its diff shows [`package.json`](https://github.com/Alhadis/language-sed/blob/f651f8bb9c69e78b274593928a66187d9ff666f0/package.json#L3) being updated with a version of `"1.0.0"` instead of `"v1.0.0"`.
3. Retag the damn release
4. Force-push the amended commit and "new" tag to GitHub
5. Run `apm publish --tag v1.0.0`
6. Cross my fingers and pray it goes through

### Versions
~~~console
$ atom --version
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
[31mapm[39m  [31m1.19.0[39m
[32mnpm[39m  [32m3.10.10[39m
[34mnode[39m [34m6.9.5[39m [34mx64[39m
[36matom[39m [36m1.25.1[39m
[33mpython[39m [33m2.7.10[39m
[35mgit[39m [35m2.17.0[39m
~~~

I'll leave the ANSI escape codes embedded in `apm`'s output above. The colours shouldn't be there even when I'm *not* piping the output to my clipboard.

**Comment by Arcanemagus** [comment]
Where did the tag and commit it references come from? `apm` uses `npm` internally to generate those commits, and `npm` doesn't create version numbers with a `v` in front in `package.json`.

* `apm publish --tag <foo>` simply attempts to use a pre-existing tag named `<foo>`. If you want automated behavior you should be using `apm publish <patch|minor|major>`
* `package.json` should _never_ have a `v` at the start of the version number.

**Comment by Alhadis** [comment]
I ran the shell commands myself, by hand, along with the usual routine audits I always do prior to publishing a release of anything I've written.

I adamantly refuse to use `apm` or `npm` to generate *anything* for me, because they molest the formatting of `package.json` to use those bullshit 2-space tabstops I love to hate so much. All I want to do is publish a release I've tagged and prepared myself – but unlike `npm`, `apm` doesn't let you run `apm publish` and have everything logically go where it has to go.

> `package.json` should *never* have a `v` at the start of the version number.

According to who? Sorry, but if authors choose to format their version strings the same way they format what they pass to `git tag -s`, they have every right to maintain that consistency.

**Comment by thomasjo** [comment]
> > package.json should never have a v at the start of the version number.
> 
> According to who? Sorry, but if authors choose to format their version strings the same way they format what they pass to git tag -s, they have every right to maintain that consistency.

@Alhadis It's an npm [requirement](https://docs.npmjs.com/getting-started/using-a-package.json#requirements). If you want to change that requirement, you'll have to open an issue on the [npm repo](https://github.com/npm/npm).

Since this issue seems to be entirely based on the premise that version specification is essentially free-form, but actually has a strict semver-like requirement in npm, I'm closing this. If there are other specific problems you're having, either open new issues or update this issue with the remaining problems.

**Comment by Alhadis** [comment]
> It's an npm [requirement](https://docs.npmjs.com/getting-started/using-a-package.json#requirements). If you want to change that **requirement**,

@thomasjo Really? Somebody at NPM has some explaining to do, then...

* [`urw-core35-fonts`](https://www.npmjs.com/package/urw-core35-fonts)@[`v1.1.0`](https://github.com/Alhadis/URW-Core35-Fonts/blob/2c74d301ff6eff298100eda2152c9b8bcc211bfc/package.json#L3)
* [`atom-mocha`](https://www.npmjs.com/package/atom-mocha)@[`v2.0.5`](https://github.com/Alhadis/Atom-Mocha/blob/a82a35348b9ab5f23a290db8002d60662e364948/package.json#L3)
* [`alhadis.utils`](https://www.npmjs.com/package/alhadis.utils)@[`v0.1.3`](https://github.com/Alhadis/Utils/blob/766e200623b608fc560dbe507db6f39dcf9fe11f/package.json#L3)
* [`ppjson`](https://www.npmjs.com/package/ppjson)@[`v1.4.0`](https://github.com/Alhadis/PPJSON/blob/2374500c02cfbedadf2ec06da4db1f60f1769be3/package.json#L3)

Want me to [keep going](https://www.npmjs.com/~alhadis)?

**Comment by Alhadis** [comment]
@thomasjo Try this too:

~~~console
$ npm -g install semver
$ semver v1.3.0 1.0.0
1.0.0
1.3.0
$ semver v1.3.0 1.0
1.3.0
$ semver x1.3.0
No output, exits with an error code
~~~

Also, where did this come from?

> Since this issue seems to be entirely based on the premise that **version specification is essentially free-form**, but actually has a **strict semver-like** requirement

As usual, you're being condescending and assuming pretty daft ignorance on my part. I'll actually  quote the words [from the spec](https://semver.org/#semantic-versioning-specification-semver) you've attempted to rules-lawyer:

> 2. A normal **version number** MUST take the form X.Y.Z where X, Y, and Z are **non-negative integers**

Semver specifies the relationship between numeric values and human-assigned meaning ("semantics"), as explained in [the summary](https://semver.org/#introduction):

> ... a simple set of rules and requirements that dictate how **version numbers** are **assigned** and **incremented**

A prefix of `v` doesn't change or alter the perceived meaning of a valid semver number.

**Comment by lee-dohm** [comment]
I can understand your frustration in trying to get apm to do what you want. We've designed it with the intention to be as easy as possible for newcomers at the cost of it having some arcane hoops to jump through if you choose to do everything manually. Whether we're successful or not at that ease-of-use is, of course, up for debate and a matter of opinion.

As I often state though, apm is not npm. Because some parts of the Atom infrastructure make assumptions around things based on the version number being a certain format, we've tried to make the error messages more informative when people stumble across these edge cases.

For the record:

1. The `version` value in the `package.json` of an Atom package must be of the format `X.Y.Z` with no leading `v`
1. The tag pointing to the release must be of the format `vX.Y.Z`, in other words it must include the leading `v`

I'll see what I can do to document atom.io's requirements for manually publishing in [the Flight Manual section on maintaining your packages.](https://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/) I hope that will help avoid misunderstandings like this in the future.
