### ISSUE TITLE
apm unpublish unauthorized

### ISSUE THREAD

**Issue by AkihiroWatanabeUW** [atom/apm#811]
I have removed the github repo, please remove the package.
https://atom.io/packages/xaiml-editor

I'd like to republish it. But it doesn't authorized to unpublish.
`
apm unpublish xaiml-editor
Are you sure you want to unpublish ALL VERSIONS of 'xaiml-editor'? This will remove it from the apm registry, including download counts and stars, and this action is irreversible. (no)yes
Unpublishing xaiml-editor failed
Unpublishing failed: Unauthorized
`
Thanks,

**Comment by rsese** [comment]
Just to clarify, you could publish now under a different package name but you want to publish again using the `xaiml-editor` package name?

**Comment by AkihiroWatanabeUW** [comment]
Hi, thanks for your response. Yes, that's right. Although I can publish a different package, I really want to use the xaiml-editor again.
Regards,

**Comment by rsese** [comment]
Sorry for losing track of this - it sounds looks like you're running into the same issue referenced in https://github.com/atom/apm/issues/809#issuecomment-414657228 where the package is associated with a now deleted repository.  I'm not sure what the original repository was since `docomo-dialog/xaiml-editor` was deleted and recreated multiple times but the current `docomo-dialog/xaiml-editor` repository was created at 2018-09-12T04:28:03Z and has GitHub repository ID 148421384.

I'll ask our engineers to take a look and we'll followup when we have news to share.

**Comment by rsese** [comment]
@AkihiroWatanabeUW: our engineers updated the  package registry so that the `xaiml-editor` package now points at the `docomo-dialog/xaiml-editor` repository with ID 148421384 I mentioned above.

Can you try publishing again and let us know if you have any trouble?

**Comment by AkihiroWatanabeUW** [comment]
Thanks for your update. I could publish correctly!!

**Comment by rsese** [comment]
Great thanks for confirming :+1:  Since this is resolved, we'll go ahead and close the issue.
