### ISSUE TITLE
BUILD_FROM_SRC_DOC_AND_DOCKERIZED_STANDALONE_APM

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [atom/apm#871]
## Summary

I recently checked that the Build From Source Documentation of `APM`, is severely lacking infos. For instance : 
* I found no where any explanation on how to tie `APM` up with `NodeJS` runtime, 
*  And no where explanations about the Python Environment that should be set to a `2.7` release version (latest update)

All in alll, you'll find all you need to manage this issue at : https://github.com/Jean-Baptiste-Lasselle/apm-dokerized-build-from-source

## Motivation

Well i wanted to make hot configuration possible, meaning up to hot package reloading

I open this issue to quickly share the work I already achieved, an automated APM Build From Source.The recipe also shows how to standalone run APM, see : https://github.com/Jean-Baptiste-Lasselle/apm-dokerized-build-from-source

## Describe alternatives you've considered

Eclipse Che

## Additional context

...

**Comment by Jean-Baptiste-Lasselle** [comment]
I add that Python 2.7 has reached EOL, so what about Atom IDE ?

**Comment by Arcanemagus** [comment]
> I found no where any explanation on how to tie APM up with NodeJS runtime

`apm` is the _Atom_ package manager, it's not intended to be something that is done as a standalone package. When bundled with Atom it has an appropriate Node.js runtime packaged with it.

> And no where explanations about the Python Environment that should be set to a 2.7 release version (latest update)

You haven't provided any information on what errors you were seeing that led you to this, but I'm guessing that you were running into the ever present `node-gyp` issue with Python 3, which has nothing to do with Atom (or `apm`) specifically, and is a Node.js ecosystem wide issue.

> I add that Python 2.7 has reached EOL, so what about Atom IDE ?

Atom itself has no dependency on Python, other than the previously mentioned `node-gyp` issue.

----

> Well i wanted to make hot configuration possible, meaning up to hot package reloading

`apm` has almost nothing to do with this (other than installing the updated files), that's an issue entirely within Atom. Atom actually used to have live reloading for packages, but the edge cases surrounding it proved too unreliable to **guarantee** that things were reloaded correctly, so Atom now requires a restart in order to bring in the new package version.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @Arcanemagus ,

Thank you so much for this quick and extensive answer !

Actually, I did understand that APM was not meant to be run on standalone, and I wrote my issue more to share an opportunity rather than pointing out an issue.

I also point the Python 2.7 EOL issue, because it is important, and so interesting, very much so indeed : 

> 
> Atom itself has no dependency on Python, other than the previously mentioned `node-gyp` issue.
> 

Well it's word (to be or not to be, that is not the question) : 

* I agree, when you _run_ `atom` or `apm` standalone (because it's now possible, cf. my repo), you **don't** bring (hence execute) any `python2` runtime aboard.
* Yes, I, at some point, had an `node-gyp` issue, and resolved it. So thank you for pointing that out, and giving more well known details about it.
* Yet, whether `node-gyp`, or whoever might be responsible for it, I care first about your awesome  work, `Atom`, which I fell in love with. Caring that much means I had to spawn up a repo and gives a proof that Atom 's Pipeline has Python 2 as a dependency.
* So yes, Atom doesn't run it, but soon, no pipeline will run Python2, and my biggest clients' Security Engineer will not care all I brought in thanks to `Atom`, they'll just cut it off their Information System. I don't wanna go back to Eclipse :) .   
* Oh , I have to mention one important thing : every time I bring in `Atom` into my clients company, I bring it with 100% sovereignty . Meaning I import all 254 repos in   https://github.com/atom/, inside the company, and add my devops work, to make it an autonomous Software factory. Theycan build from source on the inside, and security engineers can't block my work anymore, because it's integrated with an ISO 27000 security management process (security reviews, OCI image vulnerability scanners, and so on (and other reasons, but not first, why i dockerized every single package).  
* Meaning also I have actually designed https://github.com/Jean-Baptiste-Lasselle/apm-dokerized-build-from-source months ago for a customer, and shared that just days ago, a few commits to give first explanations. I had to share.
* As last point, I think that there might be some very unexpected interesting technical issue hidden under there, no one is responsible for, just something new.

To finish with that, you wouldn't imagine the crazy things I ended up doing, after tearing off APM that way. It was a decisive moment in my project wit my customer : 

SO what I'll do I'll share as soon as possible with the community a work I 'm currently finishing, I'll say when done. Will take weeks, I am now sick at home, and will have to work a lot for a customer when I'm back on foot. I hope before Christmas. 

And I love `Atom`, honestly, you guys changed my life with my keyboard !

**Comment by Jean-Baptiste-Lasselle** [comment]
@Arcanemagus As sson as I have respawaned My different tests, i'll give you details about : 
  * the error indeed mentioning `node-gyp`
  * and I can tell you already that I run APM in a node Docker image. An official node docker image; and instead of setting  `NODE_PATH`, which I wanted to avoid caus I wanna leave Node Enviornment manageent all left to NVM, no tricking with Node, I did this : 
  * Ok, APM is looking for node executable at path `wedontcarewhattheexactpathis`
  * And on the other hand, inside the  node official docker image, the `node` executable is at path `dontcaremuchmoreeither`
  * So guess what I did ?  
```bash
ln -s $EMBEDDED_NODE_HOME/node /pipeline/ops/bin/node
# where EMBEDDED_NODE_HOME is the folder, inside
# the NodeJS official Docker image, where the [node] executable is located on Filesystem
```
  * And there I ended up in a new world of marvels...
  * https://github.com/Jean-Baptiste-Lasselle/apm-dokerized-build-from-source/blob/392d38860f25a1461f2d2c491b976019cf9b9ac9/docker/autre3/Dockerfile#L118

**Comment by Jean-Baptiste-Lasselle** [comment]
.. https://github.com/atom/apm/issues/475

**Comment by Arcanemagus** [comment]
Since it sounds like that answered your question, and there isn't an issue with `apm` as it is used in Atom here, I'm going to close this issue.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by Jean-Baptiste-Lasselle** [comment]
https://github.com/Jean-Baptiste-Lasselle/apm-dokerized-build-from-source/raw/master/documentation/issues/images/ATOM_TEAM_SLACK_DOWN_Firefox_Screenshot_2019-10-22T10-05-14.135Z.png

> Since it sounds like that answered your question, and there isn't an issue with `apm` as it is used in Atom here, I'm going to close this issue.
> 
> Thanks for reaching out!
> 
> Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:
> 
>     * User Documentation — [The Atom Flight Manual](http://flight-manual.atom.io)
> 
>     * Developer Documentation — [Atom API Documentation](https://atom.io/docs/api/latest)
> 
>     * FAQ — [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
> 
>     * Message Board — [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
> 
>     * Chat — [Join the Atom Slack team](http://atom-slack.herokuapp.com/)
> 
> 
> On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

@Arcanemagus Thank you for your answer, which brings unexpected support to the point of view I here shared : 

![You know, it's always like that, I just happen to fall on those things on first click ...](https://github.com/Jean-Baptiste-Lasselle/apm-dokerized-build-from-source/raw/master/documentation/issues/images/ATOM_TEAM_SLACK_DOWN_Firefox_Screenshot_2019-10-22T10-05-14.135Z.png)

**Comment by Jean-Baptiste-Lasselle** [comment]
https://github.com/atom/apm/blob/master/src/generator/safemake.py
