### ISSUE TITLE
atom-beautify package not installing due to apm

### ISSUE THREAD

**Issue by zerodark088888** [atom/apm#881]
idk what is  issue but i m using atom latest version
and i cant install package name atom-beautify due to bluebird and everytime it  take alot of time to reinstall but still not working yet
idk reason but can u fix atom apm to install package fast and to work with much issues

**Comment by lkashef** [comment]
Thanks for contributing!

It appears that this is being caused by the [name of package](link to package) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
